### ISSUE TITLE
Can't unselect spell categories

### ISSUE THREAD

**Issue by MiachofTD** [ACEmulator/ACE#1145]
### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.

Create character, log into server, go to the spells list tab and un-dot a magic type like creature, life, item, war, and so on.  Server crashes.

### The log given by the failure.

Unhandled Exception: System.FormatException: Format string can be only "G", "g",
 "X", "x", "F", "f", "D" or "d".
   at System.Enum.ToString(String format)
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, Str
ing format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, Params
Array args)
   at ACE.Server.Network.Managers.InboundMessageManager.HandleGameAction(GameAct
ionType opcode, ClientMessage message, Session session) in C:\Users\Administrato
r\Desktop\ACE-daaac0e44024ce862c4875355006c75f4bf7ea7a\Source\ACE.Server\Network
\Managers\InboundMessageManager.cs:line 124
   at ACE.Server.Entity.Actions.ActionEventDelegate.Act() in C:\Users\Administra
tor\Desktop\ACE-daaac0e44024ce862c4875355006c75f4bf7ea7a\Source\ACE.Server\Entit
y\Actions\ActionEventDelegate.cs:line 16
   at ACE.Server.Entity.Actions.ActionQueue.RunActions() in C:\Users\Administrat
or\Desktop\ACE-daaac0e44024ce862c4875355006c75f4bf7ea7a\Source\ACE.Server\Entity
\Actions\ActionQueue.cs:line 20
   at ACE.Server.Managers.WorldManager.UpdateWorld() in C:\Users\Administrator\D
esktop\ACE-daaac0e44024ce862c4875355006c75f4bf7ea7a\Source\ACE.Server\Managers\W
orldManager.cs:line 372
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
ntext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
### Mention any other details that might be useful.

https://youtu.be/AS-W8oTdabQ

**Comment by gmriggs** [comment]
Fixed in https://github.com/ACEmulator/ACE/pull/1148
