### ISSUE TITLE
Server box rapid errors when attacking Crystal Spur

### ISSUE THREAD

**Issue by MiachofTD** [ACEmulator/ACE#1173]
### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.

Attack a crystal spur on open landscape.
### The log given by the failure.

Will add to comment as it is quite long.
### Mention any other details that might be useful.

Please see attached video - https://youtu.be/NHEnDA015yg

**Comment by MiachofTD** [comment]
r\Desktop\ACE-master\Source\ACE.Server\Physics\PhysicsObj.cs:line 2347
   at ACE.Server.Physics.PhysicsObj.SetPositionInternal(Transition transition) i
n C:\Users\Administrator\Desktop\ACE-master\Source\ACE.Server\Physics\PhysicsObj
.cs:line 1179
   at ACE.Server.Physics.PhysicsObj.UpdateObjectInternal(Double quantum) in C:\U
sers\Administrator\Desktop\ACE-master\Source\ACE.Server\Physics\PhysicsObj.cs:li
ne 1498
   at ACE.Server.Physics.PhysicsObj.update_object() in C:\Users\Administrator\De
sktop\ACE-master\Source\ACE.Server\Physics\PhysicsObj.cs:line 3749
   at ACE.Server.WorldObjects.WorldObject.UpdateObjectPhysics() in C:\Users\Admi
nistrator\Desktop\ACE-master\Source\ACE.Server\WorldObjects\WorldObject_Tick.cs:
line 196
   at ACE.Server.Managers.WorldManager.HandlePhysicsLandblock(Landblock landbloc
k, Double timeTick, ConcurrentQueue`1 movedObjects) in C:\Users\Administrator\De
sktop\ACE-master\Source\ACE.Server\Managers\WorldManager.cs:line 487
   at ACE.Server.Managers.WorldManager.HandlePhysics(Double timeTick) in C:\User
s\Administrator\Desktop\ACE-master\Source\ACE.Server\Managers\WorldManager.cs:li
ne 454
2018-12-22 12:47:20,887 ERROR: System.InvalidOperationException: Nullable object
 must have a value.
   at ACE.Server.WorldObjects.Player.DamageTarget(Creature target, WorldObject d
amageSource) in C:\Users\Administrator\Desktop\ACE-master\Source\ACE.Server\Worl
dObjects\Player_Combat.cs:line 149
   at ACE.Server.WorldObjects.Projectile.OnCollideObject(WorldObject target) in
C:\Users\Administrator\Desktop\ACE-master\Source\ACE.Server\WorldObjects\Project
ile.cs:line 52
   at ACE.Server.Physics.Common.WeenieObject.DoCollision(AtkCollisionProfile pro
f, ObjectGuid guid, PhysicsObj target) in C:\Users\Administrator\Desktop\ACE-mas
ter\Source\ACE.Server\Physics\Common\WeenieObject.cs:line 106
   at ACE.Server.Physics.PhysicsObj.report_object_collision(PhysicsObj obj, Bool
ean prev_has_contact) in C:\Users\Administrator\Desktop\ACE-master\Source\ACE.Se
rver\Physics\PhysicsObj.cs:line 2963
   at ACE.Server.Physics.PhysicsObj.handle_all_collisions(CollisionInfo collisio
ns, Boolean prev_has_contact, Boolean prev_on_walkable) in C:\Users\Administrato
r\Desktop\ACE-master\Source\ACE.Server\Physics\PhysicsObj.cs:line 2347
   at ACE.Server.Physics.PhysicsObj.SetPositionInternal(Transition transition) i
n C:\Users\Administrator\Desktop\ACE-master\Source\ACE.Server\Physics\PhysicsObj
.cs:line 1179
   at ACE.Server.Physics.PhysicsObj.UpdateObjectInternal(Double quantum) in C:\U
sers\Administrator\Desktop\ACE-master\Source\ACE.Server\Physics\PhysicsObj.cs:li
ne 1498
   at ACE.Server.Physics.PhysicsObj.update_object() in C:\Users\Administrator\De
sktop\ACE-master\Source\ACE.Server\Physics\PhysicsObj.cs:line 3749
   at ACE.Server.WorldObjects.WorldObject.UpdateObjectPhysics() in C:\Users\Admi
nistrator\Desktop\ACE-master\Source\ACE.Server\WorldObjects\WorldObject_Tick.cs:
line 196
   at ACE.Server.Managers.WorldManager.HandlePhysicsLandblock(Landblock landbloc
k, Double timeTick, ConcurrentQueue`1 movedObjects) in C:\Users\Administrator\De
sktop\ACE-master\Source\ACE.Server\Managers\WorldManager.cs:line 487
   at ACE.Server.Managers.WorldManager.HandlePhysics(Double timeTick) in C:\User
s\Administrator\Desktop\ACE-master\Source\ACE.Server\Managers\WorldManager.cs:li
ne 454
2018-12-22 12:47:20,981 ERROR: System.InvalidOperationException: Nullable object
 must have a value.
   at ACE.Server.WorldObjects.Player.DamageTarget(Creature target, WorldObject d
amageSource) in C:\Users\Administrator\Desktop\ACE-master\Source\ACE.Server\Worl
dObjects\Player_Combat.cs:line 149
   at ACE.Server.WorldObjects.Projectile.OnCollideObject(WorldObject target) in
C:\Users\Administrator\Desktop\ACE-master\Source\ACE.Server\WorldObjects\Project
ile.cs:line 52
   at ACE.Server.Physics.Common.WeenieObject.DoCollision(AtkCollisionProfile pro
f, ObjectGuid guid, PhysicsObj target) in C:\Users\Administrator\Desktop\ACE-mas
ter\Source\ACE.Server\Physics\Common\WeenieObject.cs:line 106
   at ACE.Server.Physics.PhysicsObj.report_object_collision(PhysicsObj obj, Bool
ean prev_has_contact) in C:\Users\Administrator\Desktop\ACE-master\Source\ACE.Se
rver\Physics\PhysicsObj.cs:line 2963
   at ACE.Server.Physics.PhysicsObj.handle_all_collisions(CollisionInfo collisio
ns, Boolean prev_has_contact, Boolean prev_on_walkable) in C:\Users\Administrato
r\Desktop\ACE-master\Source\ACE.Server\Physics\PhysicsObj.cs:line 2347
   at ACE.Server.Physics.PhysicsObj.SetPositionInternal(Transition transition) i
n C:\Users\Administrator\Desktop\ACE-master\Source\ACE.Server\Physics\PhysicsObj
.cs:line 1179
   at ACE.Server.Physics.PhysicsObj.UpdateObjectInternal(Double quantum) in C:\U
sers\Administrator\Desktop\ACE-master\Source\ACE.Server\Physics\PhysicsObj.cs:li
ne 1498
   at ACE.Server.Physics.PhysicsObj.update_object() in C:\Users\Administrator\De
sktop\ACE-master\Source\ACE.Server\Physics\PhysicsObj.cs:line 3749
   at ACE.Server.WorldObjects.WorldObject.UpdateObjectPhysics() in C:\Users\Admi
nistrator\Desktop\ACE-master\Source\ACE.Server\WorldObjects\WorldObject_Tick.cs:
line 196
   at ACE.Server.Managers.WorldManager.HandlePhysicsLandblock(Landblock landbloc
k, Double timeTick, ConcurrentQueue`1 movedObjects) in C:\Users\Administrator\De
sktop\ACE-master\Source\ACE.Server\Managers\WorldManager.cs:line 487
   at ACE.Server.Managers.WorldManager.HandlePhysics(Double timeTick) in C:\User
s\Administrator\Desktop\ACE-master\Source\ACE.Server\Managers\WorldManager.cs:li
ne 454
2018-12-22 12:47:21,047 ERROR: System.InvalidOperationException: Nullable object
 must have a value.
   at ACE.Server.WorldObjects.Player.DamageTarget(Creature target, WorldObject d
amageSource) in C:\Users\Administrator\Desktop\ACE-master\Source\ACE.Server\Worl
dObjects\Player_Combat.cs:line 149
   at ACE.Server.WorldObjects.Projectile.OnCollideObject(WorldObject target) in
C:\Users\Administrator\Desktop\ACE-master\Source\ACE.Server\WorldObjects\Project
ile.cs:line 52
   at ACE.Server.Physics.Common.WeenieObject.DoCollision(AtkCollisionProfile pro
f, ObjectGuid guid, PhysicsObj target) in C:\Users\Administrator\Desktop\ACE-mas
ter\Source\ACE.Server\Physics\Common\WeenieObject.cs:line 106
   at ACE.Server.Physics.PhysicsObj.report_object_collision(PhysicsObj obj, Bool
ean prev_has_contact) in C:\Users\Administrator\Desktop\ACE-master\Source\ACE.Se
rver\Physics\PhysicsObj.cs:line 2963
   at ACE.Server.Physics.PhysicsObj.handle_all_collisions(CollisionInfo collisio
ns, Boolean prev_has_contact, Boolean prev_on_walkable) in C:\Users\Administrato
r\Desktop\ACE-master\Source\ACE.Server\Physics\PhysicsObj.cs:line 2347
   at ACE.Server.Physics.PhysicsObj.SetPositionInternal(Transition transition) i
n C:\Users\Administrator\Desktop\ACE-master\Source\ACE.Server\Physics\PhysicsObj
.cs:line 1179
   at ACE.Server.Physics.PhysicsObj.UpdateObjectInternal(Double quantum) in C:\U
sers\Administrator\Desktop\ACE-master\Source\ACE.Server\Physics\PhysicsObj.cs:li
ne 1498
   at ACE.Server.Physics.PhysicsObj.update_object() in C:\Users\Administrator\De
sktop\ACE-master\Source\ACE.Server\Physics\PhysicsObj.cs:line 3749
   at ACE.Server.WorldObjects.WorldObject.UpdateObjectPhysics() in C:\Users\Admi
nistrator\Desktop\ACE-master\Source\ACE.Server\WorldObjects\WorldObject_Tick.cs:
line 196
   at ACE.Server.Managers.WorldManager.HandlePhysicsLandblock(Landblock landbloc
k, Double timeTick, ConcurrentQueue`1 movedObjects) in C:\Users\Administrator\De
sktop\ACE-master\Source\ACE.Server\Managers\WorldManager.cs:line 487
   at ACE.Server.Managers.WorldManager.HandlePhysics(Double timeTick) in C:\User
s\Administrator\Desktop\ACE-master\Source\ACE.Server\Managers\WorldManager.cs:li
ne 454
2018-12-22 12:48:36,233 ERROR: System.InvalidOperationException: Nullable object
 must have a value.
   at ACE.Server.WorldObjects.Player.DamageTarget(Creature target, WorldObject d
amageSource) in C:\Users\Administrator\Desktop\ACE-master\Source\ACE.Server\Worl
dObjects\Player_Combat.cs:line 149
   at ACE.Server.WorldObjects.Projectile.OnCollideObject(WorldObject target) in
C:\Users\Administrator\Desktop\ACE-master\Source\ACE.Server\WorldObjects\Project
ile.cs:line 52
   at ACE.Server.Physics.Common.WeenieObject.DoCollision(AtkCollisionProfile pro
f, ObjectGuid guid, PhysicsObj target) in C:\Users\Administrator\Desktop\ACE-mas
ter\Source\ACE.Server\Physics\Common\WeenieObject.cs:line 106
   at ACE.Server.Physics.PhysicsObj.report_object_collision(PhysicsObj obj, Bool
ean prev_has_contact) in C:\Users\Administrator\Desktop\ACE-master\Source\ACE.Se
rver\Physics\PhysicsObj.cs:line 2963
   at ACE.Server.Physics.PhysicsObj.handle_all_collisions(CollisionInfo collisio
ns, Boolean prev_has_contact, Boolean prev_on_walkable) in C:\Users\Administrato
r\Desktop\ACE-master\Source\ACE.Server\Physics\PhysicsObj.cs:line 2347
   at ACE.Server.Physics.PhysicsObj.SetPositionInternal(Transition transition) i
n C:\Users\Administrator\Desktop\ACE-master\Source\ACE.Server\Physics\PhysicsObj
.cs:line 1179
   at ACE.Server.Physics.PhysicsObj.UpdateObjectInternal(Double quantum) in C:\U
sers\Administrator\Desktop\ACE-master\Source\ACE.Server\Physics\PhysicsObj.cs:li
ne 1498
   at ACE.Server.Physics.PhysicsObj.update_object() in C:\Users\Administrator\De
sktop\ACE-master\Source\ACE.Server\Physics\PhysicsObj.cs:line 3758
   at ACE.Server.WorldObjects.WorldObject.UpdateObjectPhysics() in C:\Users\Admi
nistrator\Desktop\ACE-master\Source\ACE.Server\WorldObjects\WorldObject_Tick.cs:
line 196
   at ACE.Server.Managers.WorldManager.HandlePhysicsLandblock(Landblock landbloc
k, Double timeTick, ConcurrentQueue`1 movedObjects) in C:\Users\Administrator\De
sktop\ACE-master\Source\ACE.Server\Managers\WorldManager.cs:line 487
   at ACE.Server.Managers.WorldManager.HandlePhysics(Double timeTick) in C:\User
s\Administrator\Desktop\ACE-master\Source\ACE.Server\Managers\WorldManager.cs:li
ne 454
2018-12-22 12:48:38,468 ERROR: System.InvalidOperationException: Nullable object
 must have a value.
   at ACE.Server.WorldObjects.Player.DamageTarget(Creature target, WorldObject d
amageSource) in C:\Users\Administrator\Desktop\ACE-master\Source\ACE.Server\Worl
dObjects\Player_Combat.cs:line 149
   at ACE.Server.WorldObjects.Projectile.OnCollideObject(WorldObject target) in
C:\Users\Administrator\Desktop\ACE-master\Source\ACE.Server\WorldObjects\Project
ile.cs:line 52
   at ACE.Server.Physics.Common.WeenieObject.DoCollision(AtkCollisionProfile pro
f, ObjectGuid guid, PhysicsObj target) in C:\Users\Administrator\Desktop\ACE-mas
ter\Source\ACE.Server\Physics\Common\WeenieObject.cs:line 106
   at ACE.Server.Physics.PhysicsObj.report_object_collision(PhysicsObj obj, Bool
ean prev_has_contact) in C:\Users\Administrator\Desktop\ACE-master\Source\ACE.Se
rver\Physics\PhysicsObj.cs:line 2963
   at ACE.Server.Physics.PhysicsObj.handle_all_collisions(CollisionInfo collisio
ns, Boolean prev_has_contact, Boolean prev_on_walkable) in C:\Users\Administrato
r\Desktop\ACE-master\Source\ACE.Server\Physics\PhysicsObj.cs:line 2347
   at ACE.Server.Physics.PhysicsObj.SetPositionInternal(Transition transition) i
n C:\Users\Administrator\Desktop\ACE-master\Source\ACE.Server\Physics\PhysicsObj
.cs:line 1179
   at ACE.Server.Physics.PhysicsObj.UpdateObjectInternal(Double quantum) in C:\U
sers\Administrator\Desktop\ACE-master\Source\ACE.Server\Physics\PhysicsObj.cs:li
ne 1498
   at ACE.Server.Physics.PhysicsObj.update_object() in C:\Users\Administrator\De
sktop\ACE-master\Source\ACE.Server\Physics\PhysicsObj.cs:line 3758
   at ACE.Server.WorldObjects.WorldObject.UpdateObjectPhysics() in C:\Users\Admi
nistrator\Desktop\ACE-master\Source\ACE.Server\WorldObjects\WorldObject_Tick.cs:
line 196
   at ACE.Server.Managers.WorldManager.HandlePhysicsLandblock(Landblock landbloc
k, Double timeTick, ConcurrentQueue`1 movedObjects) in C:\Users\Administrator\De
sktop\ACE-master\Source\ACE.Server\Managers\WorldManager.cs:line 487
   at ACE.Server.Managers.WorldManager.HandlePhysics(Double timeTick) in C:\User
s\Administrator\Desktop\ACE-master\Source\ACE.Server\Managers\WorldManager.cs:li
ne 454
2018-12-22 12:48:57,651 ERROR: System.InvalidOperationException: Nullable object
 must have a value.
   at ACE.Server.WorldObjects.Player.DamageTarget(Creature target, WorldObject d
amageSource) in C:\Users\Administrator\Desktop\ACE-master\Source\ACE.Server\Worl
dObjects\Player_Combat.cs:line 149
   at ACE.Server.WorldObjects.Projectile.OnCollideObject(WorldObject target) in
C:\Users\Administrator\Desktop\ACE-master\Source\ACE.Server\WorldObjects\Project
ile.cs:line 52
   at ACE.Server.Physics.Common.WeenieObject.DoCollision(AtkCollisionProfile pro
f, ObjectGuid guid, PhysicsObj target) in C:\Users\Administrator\Desktop\ACE-mas
ter\Source\ACE.Server\Physics\Common\WeenieObject.cs:line 106
   at ACE.Server.Physics.PhysicsObj.report_object_collision(PhysicsObj obj, Bool
ean prev_has_contact) in C:\Users\Administrator\Desktop\ACE-master\Source\ACE.Se
rver\Physics\PhysicsObj.cs:line 2963
   at ACE.Server.Physics.PhysicsObj.handle_all_collisions(CollisionInfo collisio
ns, Boolean prev_has_contact, Boolean prev_on_walkable) in C:\Users\Administrato
r\Desktop\ACE-master\Source\ACE.Server\Physics\PhysicsObj.cs:line 2347
   at ACE.Server.Physics.PhysicsObj.SetPositionInternal(Transition transition) i
n C:\Users\Administrator\Desktop\ACE-master\Source\ACE.Server\Physics\PhysicsObj
.cs:line 1179
   at ACE.Server.Physics.PhysicsObj.UpdateObjectInternal(Double quantum) in C:\U
sers\Administrator\Desktop\ACE-master\Source\ACE.Server\Physics\PhysicsObj.cs:li
ne 1498
   at ACE.Server.Physics.PhysicsObj.update_object() in C:\Users\Administrator\De
sktop\ACE-master\Source\ACE.Server\Physics\PhysicsObj.cs:line 3758
   at ACE.Server.WorldObjects.WorldObject.UpdateObjectPhysics() in C:\Users\Admi
nistrator\Desktop\ACE-master\Source\ACE.Server\WorldObjects\WorldObject_Tick.cs:
line 196
   at ACE.Server.Managers.WorldManager.HandlePhysicsLandblock(Landblock landbloc
k, Double timeTick, ConcurrentQueue`1 movedObjects) in C:\Users\Administrator\De
sktop\ACE-master\Source\ACE.Server\Managers\WorldManager.cs:line 487
   at ACE.Server.Managers.WorldManager.HandlePhysics(Double timeTick) in C:\User
s\Administrator\Desktop\ACE-master\Source\ACE.Server\Managers\WorldManager.cs:li
ne 454
2018-12-22 12:48:57,701 ERROR: System.InvalidOperationException: Nullable object
 must have a value.
   at ACE.Server.WorldObjects.Player.DamageTarget(Creature target, WorldObject d
amageSource) in C:\Users\Administrator\Desktop\ACE-master\Source\ACE.Server\Worl
dObjects\Player_Combat.cs:line 149
   at ACE.Server.WorldObjects.Projectile.OnCollideObject(WorldObject target) in
C:\Users\Administrator\Desktop\ACE-master\Source\ACE.Server\WorldObjects\Project
ile.cs:line 52
   at ACE.Server.Physics.Common.WeenieObject.DoCollision(AtkCollisionProfile pro
f, ObjectGuid guid, PhysicsObj target) in C:\Users\Administrator\Desktop\ACE-mas
ter\Source\ACE.Server\Physics\Common\WeenieObject.cs:line 106
   at ACE.Server.Physics.PhysicsObj.report_object_collision(PhysicsObj obj, Bool
ean prev_has_contact) in C:\Users\Administrator\Desktop\ACE-master\Source\ACE.Se
rver\Physics\PhysicsObj.cs:line 2963
   at ACE.Server.Physics.PhysicsObj.handle_all_collisions(CollisionInfo collisio
ns, Boolean prev_has_contact, Boolean prev_on_walkable) in C:\Users\Administrato
r\Desktop\ACE-master\Source\ACE.Server\Physics\PhysicsObj.cs:line 2347
   at ACE.Server.Physics.PhysicsObj.SetPositionInternal(Transition transition) i
n C:\Users\Administrator\Desktop\ACE-master\Source\ACE.Server\Physics\PhysicsObj
.cs:line 1179
   at ACE.Server.Physics.PhysicsObj.UpdateObjectInternal(Double quantum) in C:\U
sers\Administrator\Desktop\ACE-master\Source\ACE.Server\Physics\PhysicsObj.cs:li
ne 1498
   at ACE.Server.Physics.PhysicsObj.update_object() in C:\Users\Administrator\De
sktop\ACE-master\Source\ACE.Server\Physics\PhysicsObj.cs:line 3749
   at ACE.Server.WorldObjects.WorldObject.UpdateObjectPhysics() in C:\Users\Admi
nistrator\Desktop\ACE-master\Source\ACE.Server\WorldObjects\WorldObject_Tick.cs:
line 196
   at ACE.Server.Managers.WorldManager.HandlePhysicsLandblock(Landblock landbloc
k, Double timeTick, ConcurrentQueue`1 movedObjects) in C:\Users\Administrator\De
sktop\ACE-master\Source\ACE.Server\Managers\WorldManager.cs:line 487
   at ACE.Server.Managers.WorldManager.HandlePhysics(Double timeTick) in C:\User
s\Administrator\Desktop\ACE-master\Source\ACE.Server\Managers\WorldManager.cs:li
ne 454

Unhandled Exception: System.InvalidOperationException: Nullable object must have
 a value.
   at ACE.Server.WorldObjects.Player.DamageTarget(Creature target, WorldObject d
amageSource) in C:\Users\Administrator\Desktop\ACE-master\Source\ACE.Server\Worl
dObjects\Player_Combat.cs:line 149
   at ACE.Server.WorldObjects.Projectile.OnCollideObject(WorldObject target) in
C:\Users\Administrator\Desktop\ACE-master\Source\ACE.Server\WorldObjects\Project
ile.cs:line 52
   at ACE.Server.WorldObjects.Creature.LaunchProjectile(WorldObject ammo, WorldO
bject target, Single& time) in C:\Users\Administrator\Desktop\ACE-master\Source\
ACE.Server\WorldObjects\Creature_Missile.cs:line 100
   at ACE.Server.WorldObjects.Player.<>c__DisplayClass270_0.<LaunchMissile>b__0(
) in C:\Users\Administrator\Desktop\ACE-master\Source\ACE.Server\WorldObjects\Pl
ayer_Missile.cs:line 113
   at ACE.Server.Entity.Actions.ActionEventDelegate.Act() in C:\Users\Administra
tor\Desktop\ACE-master\Source\ACE.Server\Entity\Actions\ActionEventDelegate.cs:l
ine 16
   at ACE.Server.Entity.Actions.ActionQueue.RunActions() in C:\Users\Administrat
or\Desktop\ACE-master\Source\ACE.Server\Entity\Actions\ActionQueue.cs:line 20
   at ACE.Server.WorldObjects.WorldObject.Tick(Double currentUnixTime) in C:\Use
rs\Administrator\Desktop\ACE-master\Source\ACE.Server\WorldObjects\WorldObject_T
ick.cs:line 27
   at ACE.Server.WorldObjects.Container.Tick(Double currentUnixTime) in C:\Users
\Administrator\Desktop\ACE-master\Source\ACE.Server\WorldObjects\Container_Tick.
cs:line 12
   at ACE.Server.WorldObjects.Creature.Tick(Double currentUnixTime) in C:\Users\
Administrator\Desktop\ACE-master\Source\ACE.Server\WorldObjects\Creature_Tick.cs
:line 14
   at ACE.Server.WorldObjects.Player.Tick(Double currentUnixTime) in C:\Users\Ad
ministrator\Desktop\ACE-master\Source\ACE.Server\WorldObjects\Player_Tick.cs:lin
e 35
   at ACE.Server.Entity.Landblock.Tick(Double currentUnixTime) in C:\Users\Admin
istrator\Desktop\ACE-master\Source\ACE.Server\Entity\Landblock.cs:line 264
   at ACE.Server.Managers.WorldManager.UpdateGameWorld() in C:\Users\Administrat
or\Desktop\ACE-master\Source\ACE.Server\Managers\WorldManager.cs:line 419
   at ACE.Server.Managers.WorldManager.UpdateWorld() in C:\Users\Administrator\D
esktop\ACE-master\Source\ACE.Server\Managers\WorldManager.cs:line 376
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
ntext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

**Comment by MiachofTD** [comment]
Digging deeper show that when using a bow (haven't tested other missile yet) if you arrow misses there will be a missed message once or multiple times and for each miss message there is the error in the server window.  It stops as long as you don't miss.  Miss too many times and the server crashes.

**Comment by gmriggs** [comment]
This should be fixed in https://github.com/ACEmulator/ACE/pull/1168
