### ISSUE TITLE
The /buff Command is broken

### ISSUE THREAD

**Issue by someeodtech** [ACEmulator/ACE#1268]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
Typing /buff or /buff <player target> both produce errors

### The log given by the failure.
2019-01-13 13:08:32,910 ERROR: Exception while invoking command handler for: buff
System.ArgumentException: Requested value 'TrueValueSelf8' was not found.
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at ACE.Server.WorldObjects.Player.CreateSentinelBuffPlayers(IEnumerable`1 players, Boolean self, UInt64 maxLevel) in C:\Users\jonat\Documents\GitHub\ACE-NonProd\ACE\Source\ACE.Server\WorldObjects\Player_Magic.cs:line 979
   at ACE.Server.Command.Handlers.SentinelCommands.HandleBuff(Session session, String[] parameters) in C:\Users\jonat\Documents\GitHub\ACE-NonProd\ACE\Source\ACE.Server\Command\Handlers\SentinelCommands.cs:line 208
   at ACE.Server.Network.GameAction.Actions.GameActionTalk.Handle(ClientMessage clientMessage, Session session) in C:\Users\jonat\Documents\GitHub\ACE-NonProd\ACE\Source\ACE.Server\Network\GameAction\Actions\GameActionTalk.cs:line 52

**Comment by gmriggs** [comment]
Fixed in https://github.com/ACEmulator/ACE/pull/1275
