### ISSUE TITLE
Portal Gems still crash server

### ISSUE THREAD

**Issue by cyberkiller6** [ACEmulator/ACE#1312]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
Put a Shoyanen Portal Gem into a pack, not your main pack
try to use it

### The log given by the failure.
ERROR (ACE.Server.Program) System.NullReferenceException: Object reference not set to an instance of an object.
   at ACE.Server.WorldObjects.WorldObject.ItemMagic(WorldObject target, Spell spell, WorldObject itemCaster) in ACE.Server\WorldObjects\WorldObject_Magic.cs:line 825
   at ACE.Server.WorldObjects.WorldObject.TryCastSpell(Spell spell, WorldObject target, WorldObject caster) in ACE.Server\WorldObjects\WorldObject_Magic.cs:line 69
   at ACE.Server.WorldObjects.Gem.UseItem(Player player) in ACE.Server\WorldObjects\Gem.cs:line 108
   at ACE.Server.WorldObjects.Player.HandleActionUseItem(UInt32 itemGuid) in ACE.Server\WorldObjects\Player_Use.cs:line 162
   at ACE.Server.Network.GameAction.Actions.GameActionUseItem.Handle(ClientMessage message, Session session) in ACE.Server\Network\GameAction\Actions\GameActionUseItem.cs:line 11
   at ACE.Server.Network.Managers.InboundMessageManager.<>c__DisplayClass11_0.<HandleGameAction>b__0() in ACE.Server\Network\Managers\InboundMessageManager.cs:line 119
   at ACE.Server.Entity.Actions.ActionEventDelegate.Act() in ACE.Server\Entity\Actions\ActionEventDelegate.cs:line 16
   at ACE.Server.Entity.Actions.ActionQueue.RunActions() in ACE.Server\Entity\Actions\ActionQueue.cs:line 23
   at ACE.Server.Network.Session.TickInbound() in ACE.Server\Network\Session.cs:line 100
   at ACE.Server.Managers.WorldManager.DoSessionWork() in ACE.Server\Managers\WorldManager.cs:line 566
   at ACE.Server.Managers.WorldManager.UpdateWorld() in ACE.Server\Managers\WorldManager.cs:line 392
   at ACE.Server.Managers.WorldManager.<>c.<Initialize>b__18_0() in ACE.Server\Managers\WorldManager.cs:line 81
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

### Desired functionality.
Portal gem is consumed and casts portal to master mage

**Comment by gmriggs** [comment]
This is fixed in https://github.com/ACEmulator/ACE/pull/1315
