### ISSUE TITLE
Crash moving through Nanto

### ISSUE THREAD

**Issue by FireyJoe** [ACEmulator/ACE#1401]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.

Setup: New test character, no items picked up, nothing examined, no fighting, etc. Click world map from training academy and arrive directly at location in Nanto below:

Drop location: Your location is: 0xE63E0001[10.000000 10.000000 95.171669] 0.678557 0.000000 0.000000 0.734548

Upon moving several steps west from the location above (on road inside Nanto), server consistently crashes with message in Crash Log. Could replicate this across all characters in account and two server/world file versions (listed below). 

Crash occurred similarly entering area from from different directions outside Nanto.

### The log given by the failure.
2019-01-31 21:19:58,713 [World Manager] ERROR (ACE.Server.Program) System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at ACE.Server.Physics.Common.LandblockStruct.ConstructVertices() in D:\ACE-master 2019-01-31\ACE-master\Source\ACE.Server\Physics\Common\LandblockStruct.cs:line 337
   at ACE.Server.Physics.Common.LandblockStruct.Generate(UInt32 landblockID, Int32 cellScale, Direction transAdj) in D:\ACE-master 2019-01-31\ACE-master\Source\ACE.Server\Physics\Common\LandblockStruct.cs:line 392
   at ACE.Server.Physics.Common.LandblockStruct..ctor(CellLandblock landblock) in D:\ACE-master 2019-01-31\ACE-master\Source\ACE.Server\Physics\Common\LandblockStruct.cs:line 87
   at ACE.Server.Physics.Common.Landblock..ctor(CellLandblock landblock) in D:\ACE-master 2019-01-31\ACE-master\Source\ACE.Server\Physics\Common\Landblock.cs:line 44
   at ACE.Server.Physics.Common.LScape.get_landblock(UInt32 blockCellID) in D:\ACE-master 2019-01-31\ACE-master\Source\ACE.Server\Physics\Common\LScape.cs:line 78
   at ACE.Server.Physics.Common.Landblock.get_adjacents(Boolean reload) in D:\ACE-master 2019-01-31\ACE-master\Source\ACE.Server\Physics\Common\Landblock.cs:line 610
   at ACE.Server.Physics.Common.ObjectMaint.GetVisibleObjects(ObjCell cell) in D:\ACE-master 2019-01-31\ACE-master\Source\ACE.Server\Physics\Common\ObjectMaint.cs:line 300
   at ACE.Server.Physics.Common.ObjectMaint.GetVisibleObjectsDist(ObjCell cell) in D:\ACE-master 2019-01-31\ACE-master\Source\ACE.Server\Physics\Common\ObjectMaint.cs:line 270
   at ACE.Server.Physics.Common.ObjectMaint.get_voyeurs() in D:\ACE-master 2019-01-31\ACE-master\Source\ACE.Server\Physics\Common\ObjectMaint.cs:line 480
   at ACE.Server.Physics.PhysicsObj.get_voyeurs() in D:\ACE-master 2019-01-31\ACE-master\Source\ACE.Server\Physics\PhysicsObj.cs:line 3951
   at ACE.Server.WorldObjects.WorldObject.NotifyPlayers() in D:\ACE-master 2019-01-31\ACE-master\Source\ACE.Server\WorldObjects\WorldObject_Networking.cs:line 1277
   at ACE.Server.Entity.Landblock.AddWorldObjectInternal(WorldObject wo) in D:\ACE-master 2019-01-31\ACE-master\Source\ACE.Server\Entity\Landblock.cs:line 555
   at ACE.Server.Entity.Landblock.AddWorldObject(WorldObject wo) in D:\ACE-master 2019-01-31\ACE-master\Source\ACE.Server\Entity\Landblock.cs:line 516
   at ACE.Server.Entity.Landblock.<>c__DisplayClass72_0.<SpawnEncounters>b__0() in D:\ACE-master 2019-01-31\ACE-master\Source\ACE.Server\Entity\Landblock.cs:line 227
   at ACE.Server.Entity.Actions.ActionEventDelegate.Act() in D:\ACE-master 2019-01-31\ACE-master\Source\ACE.Server\Entity\Actions\ActionEventDelegate.cs:line 16
   at ACE.Server.Entity.Actions.ActionQueue.RunActions() in D:\ACE-master 2019-01-31\ACE-master\Source\ACE.Server\Entity\Actions\ActionQueue.cs:line 21
   at ACE.Server.Entity.Landblock.Tick(Double currentUnixTime) in D:\ACE-master 2019-01-31\ACE-master\Source\ACE.Server\Entity\Landblock.cs:line 296
   at ACE.Server.Managers.WorldManager.UpdateGameWorld() in D:\ACE-master 2019-01-31\ACE-master\Source\ACE.Server\Managers\WorldManager.cs:line 449
   at ACE.Server.Managers.WorldManager.UpdateWorld() in D:\ACE-master 2019-01-31\ACE-master\Source\ACE.Server\Managers\WorldManager.cs:line 397
   at ACE.Server.Managers.WorldManager.<>c.<Initialize>b__18_0() in D:\ACE-master 2019-01-31\ACE-master\Source\ACE.Server\Managers\WorldManager.cs:line 82
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
### Desired functionality.

N/A: bug report
![nanto crash location](https://user-images.githubusercontent.com/47234227/52100556-f44c8d80-25a5-11e9-9a9d-4e348c27fd06.jpg)

### Mention any other details that might be useful.

Server versions tested:
2019-01-16: Crash occurred as described
2019-01-31: Crash occurred as described

World Data versions tried (deleted ace_world and rebuilt db between tries):
ACE-World-Database-v0.9.12.sql: Crash occured
ACE-World-16PY-db-v0.7.3.sql: Crash occured

**Comment by Warloxx01** [comment]
Question on File Size, I last played December of 2016, the servers went down January 31, 2017 but my file sizes are...
client_cell_1.dat = 339.968
client_portal.dat = 905.216

Could this be because I didnt travel to as many places as some?or did I miss a last minute update. these are the files I ran with in December.

**Comment by gmriggs** [comment]
https://www.gdleac.com/get-started/

If you click on the 'Installing' tab, the 'Download Update' button links to
a package with the full client_cell_1.dat and client_portal.dat.

Most people didn't have a copy of the full DATs, as this would have
required running around to almost every location in the world. The files
linked above were cobbled together from the updates received from many
players.

**Comment by gmriggs** [comment]
Hey FireyJoe,

No worries, a lot of people might not have the full copies of the dats unless they ran around to every landblock in retail

We can probably add something that detects when files from the dats are missing, and provide the user with an error instead of crashing

Thanks again
