### ISSUE TITLE
Can't Remove Pathwarden Robe

### ISSUE THREAD

**Issue by Warloxx01** [ACEmulator/ACE#1451]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
Started with a fresh Server as well as a fresh DB and latest patch. Created a Character went through all the steps grab the Pathwardens key emptied the chest put on the trinket, robe and turned in the armor for my SI Keys all went well till I decided to try on a standard Aluvian robe that I had purchested for a test but when I went to remove the Pathwardens robe the server crashed. I can remove the trinket and wand no trouble.

### The log given by the failure.

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-02-18 08:50:48,954 [1] INFO  (ACE.Server.Program) Starting ACEmulator...
2019-02-18 08:50:48,974 [1] INFO  (ACE.Server.Program) Initializing ConfigManager...
2019-02-18 08:50:49,165 [1] INFO  (ACE.Server.Program) Initializing ServerManager...
2019-02-18 08:50:49,166 [1] INFO  (ACE.Server.Program) Initializing DatManager...
2019-02-18 08:50:50,371 [1] INFO  (ACE.DatLoader.DatManager) Successfully opened D:\Games\Online\ACTOD\client_cell_1.dat file, containing 805348 records
2019-02-18 08:50:50,532 [1] INFO  (ACE.DatLoader.DatManager) Successfully opened D:\Games\Online\ACTOD\client_portal.dat file, containing 79694 records
2019-02-18 08:50:50,534 [1] INFO  (ACE.DatLoader.DatManager) Successfully opened D:\Games\Online\ACTOD\client_highres.dat file, containing 2295 records
2019-02-18 08:50:50,537 [1] INFO  (ACE.DatLoader.DatManager) Successfully opened D:\Games\Online\ACTOD\client_local_English.dat file, containing 118 records
2019-02-18 08:50:50,538 [1] INFO  (ACE.Server.Program) Initializing DatabaseManager...
2019-02-18 08:50:51,507 [1] DEBUG (ACE.Database.AuthenticationDatabase) Successfully connected to ace_auth database on 127.0.0.1:3306.
2019-02-18 08:50:52,050 [1] DEBUG (ACE.Database.WorldDatabase) Successfully connected to ace_world database on 127.0.0.1:3306.
2019-02-18 08:50:53,366 [1] DEBUG (ACE.Database.ShardDatabase) Successfully connected to ace_shard database on 127.0.0.1:3306.
2019-02-18 08:50:53,366 [1] INFO  (ACE.Server.Program) Starting DatabaseManager...
2019-02-18 08:50:53,367 [1] INFO  (ACE.Server.Program) Starting PropertyManager...
2019-02-18 08:50:53,423 [1] INFO  (ACE.Server.Program) Initializing GuidManager...
2019-02-18 08:50:53,454 [1] INFO  (ACE.Server.Program) Precaching World Database Disabled...
2019-02-18 08:50:53,455 [1] INFO  (ACE.Server.Program) Initializing PlayerManager...
2019-02-18 08:50:53,790 [1] INFO  (ACE.Server.Program) Initializing HouseManager...
2019-02-18 08:50:53,795 [1] INFO  (ACE.Server.Program) Initializing InboundMessageManager...
2019-02-18 08:50:53,940 [1] INFO  (ACE.Server.Program) Initializing SocketManager...
2019-02-18 08:50:53,942 [1] DEBUG (ACE.Server.Network.ConnectionListener) ConnectionListener ctor, host 0.0.0.0 port 9000
2019-02-18 08:50:53,944 [1] INFO  (ACE.Server.Network.Managers.SocketManager) Binding ConnectionListener to 0.0.0.0:9000
2019-02-18 08:50:53,945 [1] DEBUG (ACE.Server.Network.ConnectionListener) ConnectionListener ctor, host 0.0.0.0 port 9001
2019-02-18 08:50:53,945 [1] INFO  (ACE.Server.Network.Managers.SocketManager) Binding ConnectionListener to 0.0.0.0:9001
2019-02-18 08:50:53,945 [1] DEBUG (ACE.Server.Network.ConnectionListener) Starting ConnectionListener, host 0.0.0.0 port 9000
2019-02-18 08:50:53,948 [1] DEBUG (ACE.Server.Network.ConnectionListener) Starting ConnectionListener, host 0.0.0.0 port 9001
2019-02-18 08:50:53,949 [1] INFO  (ACE.Server.Program) Initializing WorldManager...
2019-02-18 08:50:53,955 [World Manager] INFO  (ACE.Server.Managers.LandblockManager) Preloading Landblocks...
2019-02-18 08:50:53,957 [World Manager] INFO  (ACE.Server.Managers.LandblockManager) Found 5 landblock entries in PreloadedLandblocks configuration, 1 are set to preload.
2019-02-18 08:50:53,958 [1] DEBUG (ACE.Server.Managers.WorldManager) ServerTime initialized to Date: Coldeve 18, 30 P.Y.  Time: Midsong-and-Half
2019-02-18 08:50:53,959 [1] DEBUG (ACE.Server.Managers.WorldManager) Current maximum allowed sessions: 128
2019-02-18 08:50:53,959 [1] INFO  (ACE.Server.Program) Initializing EventManager...
2019-02-18 08:50:53,969 [1] DEBUG (ACE.Server.Managers.EventManager) EventManager Initalized.
2019-02-18 08:50:53,969 [1] INFO  (ACE.Server.Program) Initializing CommandManager...
2019-02-18 08:50:53,974 [World Manager] DEBUG (ACE.Server.Managers.LandblockManager) Landblock E74E, (Hebian-To (Global Events)) preloaded. IncludeAdjacents = False, Permaload = True
2019-02-18 08:50:53,974 [World Manager] DEBUG (ACE.Server.Managers.LandblockManager) Landblock A9B4FFFF specified but not enabled in config, skipping
2019-02-18 08:50:53,974 [World Manager] DEBUG (ACE.Server.Managers.LandblockManager) Landblock DA55FFFF specified but not enabled in config, skipping
2019-02-18 08:50:53,974 [World Manager] DEBUG (ACE.Server.Managers.LandblockManager) Landblock 7D64FFFF specified but not enabled in config, skipping
2019-02-18 08:50:53,974 [World Manager] DEBUG (ACE.Server.Managers.LandblockManager) Landblock 0007FFFF specified but not enabled in config, skipping
2019-02-18 08:50:53,975 [World Manager] DEBUG (ACE.Server.Managers.WorldManager) Starting UpdateWorld thread
2019-02-18 08:51:04,299 [14] DEBUG (ACE.Server.Managers.WorldManager) Login Request from 127.0.0.1:45363
2019-02-18 08:51:04,300 [14] DEBUG (ACE.Server.Managers.WorldManager) Creating new session for 127.0.0.1:45363 with id 0
2019-02-18 08:51:04,327 [5] DEBUG (ACE.Server.Network.Handlers.AuthenticationHandler) new client connected: player. setting session properties
2019-02-18 08:51:04,342 [5] INFO  (ACE.Server.Network.Handlers.AuthenticationHandler) client player connected with verified password
2019-02-18 08:51:08,546 [5] DEBUG (ACE.Server.Managers.WorldManager) GetPossessedBiotasInParallel for Black Plague took 84 ms
2019-02-18 08:51:08,839 [World Manager] DEBUG (ACE.DatLoader.DatDatabase) Unable to find object_id A8B4FFFE in Cell
2019-02-18 08:52:12,106 [19] INFO  (ACE.Server.Network.Session) Session dropped. Account: player, Player: Black Plague, Reason: PacketHeader Disconnect
2019-02-18 08:52:12,400 [19] DEBUG (ACE.Server.Managers.WorldManager) Removing session for 127.0.0.1:45363 with id 0
2019-02-18 08:52:12,401 [19] DEBUG (ACE.Server.Network.ConnectionListener) Network Socket has thrown: 10054 An existing connection was forcibly closed by the remote host
2019-02-18 08:52:12,401 [19] DEBUG (ACE.Server.Network.ConnectionListener) Network Socket has thrown: 10054 An existing connection was forcibly closed by the remote host
2019-02-18 08:52:18,358 [8] DEBUG (ACE.Server.WorldObjects.Player) Black Plague has been saved. It took 276 ms to process the request.
2019-02-18 08:55:53,448 [11] DEBUG (ACE.Server.Managers.PropertyManager) PropertyManager DoWork took 11 ms
2019-02-18 08:57:19,638 [World Manager] DEBUG (ACE.Server.Entity.Landblock) Landblock.Unload(AAB4FFFF)
2019-02-18 08:57:19,641 [World Manager] DEBUG (ACE.Server.Entity.Landblock) Landblock.Unload(A8B4FFFF)
2019-02-18 08:57:19,641 [World Manager] DEBUG (ACE.Server.Entity.Landblock) Landblock.Unload(A9B3FFFF)
2019-02-18 08:57:19,641 [World Manager] DEBUG (ACE.Server.Entity.Landblock) Landblock.Unload(A9B5FFFF)
2019-02-18 08:57:19,641 [World Manager] DEBUG (ACE.Server.Entity.Landblock) Landblock.Unload(A9B4FFFF)
2019-02-18 08:57:19,971 [World Manager] DEBUG (ACE.Server.Entity.Landblock) Landblock.Unload(A8B5FFFF)
2019-02-18 08:57:20,088 [World Manager] DEBUG (ACE.Server.Entity.Landblock) Landblock.Unload(AAB5FFFF)
2019-02-18 08:57:20,218 [World Manager] DEBUG (ACE.Server.Entity.Landblock) Landblock.Unload(A8B3FFFF)
2019-02-18 08:57:20,367 [World Manager] DEBUG (ACE.Server.Entity.Landblock) Landblock.Unload(AAB3FFFF)
2019-02-18 09:00:53,442 [14] DEBUG (ACE.Server.Managers.PropertyManager) PropertyManager DoWork took 5 ms
2019-02-18 09:04:23,793 [19] DEBUG (ACE.Server.Managers.WorldManager) Login Request from 127.0.0.1:45363
2019-02-18 09:04:23,793 [19] DEBUG (ACE.Server.Managers.WorldManager) Creating new session for 127.0.0.1:45363 with id 0
2019-02-18 09:04:23,796 [3] DEBUG (ACE.Server.Network.Handlers.AuthenticationHandler) new client connected: player. setting session properties
2019-02-18 09:04:23,796 [3] INFO  (ACE.Server.Network.Handlers.AuthenticationHandler) client player connected with verified password
2019-02-18 09:04:26,570 [3] DEBUG (ACE.Server.Managers.WorldManager) GetPossessedBiotasInParallel for Black Plague took 33 ms
2019-02-18 09:04:38,865 [World Manager] ERROR (ACE.Server.Program) System.NullReferenceException: Object reference not set to an instance of an object.
   at ACE.Server.Managers.EnchantmentManager.Dispel(BiotaPropertiesEnchantmentRegistry entry) in D:\AC Stuff\6) Server\ACE-master\Source\ACE.Server\Managers\EnchantmentManager.cs:line 423
   at ACE.Server.Managers.EnchantmentManagerWithCaching.Dispel(BiotaPropertiesEnchantmentRegistry entry) in D:\AC Stuff\6) Server\ACE-master\Source\ACE.Server\Managers\EnchantmentManagerWithCaching.cs:line 88
   at ACE.Server.WorldObjects.Creature.RemoveItemSpell(WorldObject item, UInt32 spellId, Boolean silent) in D:\AC Stuff\6) Server\ACE-master\Source\ACE.Server\WorldObjects\Creature_Magic.cs:line 198
   at ACE.Server.WorldObjects.Player.TryDequipObjectWithNetworking(ObjectGuid objectGuid, WorldObject& item, DequipObjectAction dequipObjectAction) in D:\AC Stuff\6) Server\ACE-master\Source\ACE.Server\WorldObjects\Player_Inventory.cs:line 269
   at ACE.Server.WorldObjects.Player.DoHandleActionPutItemInContainer(WorldObject item, Container itemRootOwner, Boolean itemWasEquipped, Container container, Container containerRootOwner, Int32 placement) in D:\AC Stuff\6) Server\ACE-master\Source\ACE.Server\WorldObjects\Player_Inventory.cs:line 679
   at ACE.Server.WorldObjects.Player.HandleActionPutItemInContainer(UInt32 itemGuid, UInt32 containerGuid, Int32 placement) in D:\AC Stuff\6) Server\ACE-master\Source\ACE.Server\WorldObjects\Player_Inventory.cs:line 666
   at ACE.Server.Entity.Actions.ActionEventDelegate.Act() in D:\AC Stuff\6) Server\ACE-master\Source\ACE.Server\Entity\Actions\ActionEventDelegate.cs:line 16
   at ACE.Server.Entity.Actions.ActionQueue.RunActions() in D:\AC Stuff\6) Server\ACE-master\Source\ACE.Server\Entity\Actions\ActionQueue.cs:line 21
   at ACE.Server.Managers.WorldManager.DoSessionWork() in D:\AC Stuff\6) Server\ACE-master\Source\ACE.Server\Managers\WorldManager.cs:line 587
   at ACE.Server.Managers.WorldManager.UpdateWorld() in D:\AC Stuff\6) Server\ACE-master\Source\ACE.Server\Managers\WorldManager.cs:line 416
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

**Comment by kdmxp256** [comment]
My guess, without having looked yet, is that there is a spell on the Robe that isn't being handled properly when the robe is taken off.  I will look at it this evening.

**Comment by gmriggs** [comment]
Fixed in https://github.com/ACEmulator/ACE/pull/1467
