### ISSUE TITLE
DoSaveBiota: Unknown column 'order' in 'field list'

### ISSUE THREAD

**Issue by eviosdelam** [ACEmulator/ACE#2931]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
Died.

### The log given by the failure.
Not sure if this is me, or if others are encountering.

2020-04-14 00:55:48,896 ERROR: [DATABASE] DoSaveBiota 0x80000638:Corpse of [CHARNAME] failed first attempt with exception: Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Unknown column 'order' in 'field list'
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Unknown column 'order' in 'field list'
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ResultSet.cs:line 49
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 111
   at MySql.Data.MySqlClient.MySqlDataReader.NextResultAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 91
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 28
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlConverterCommandBuilderFactory.MySqlConverterRelationalCommandBuilder.MySqlConverterRelationalCommand.MySqlConverterRelationalDataReader.MySqlConverterDataReader.NextResult()
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.Consume(RelationalDataReader reader)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.Consume(RelationalDataReader reader)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(DbContext _, ValueTuple`2 parameters)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at ACE.Database.ShardDatabase.DoSaveBiota(ShardDbContext context, Biota biota) in C:\ACE\Install\ACE-master\Source\ACE.Database\ShardDatabase.cs:line 294
2020-04-14 00:55:48,897 ERROR: [DATABASE] DoSaveBiota 0x80000638:Corpse of [CHARNAME] failed second attempt with exception: Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
...

**Comment by gmriggs** [comment]
Not a bug. Run the updates in your Database/Updates/Shard folder

**Comment by eviosdelam** [comment]
Thanks gmriggs,

 

I had run the updates to the shard, many of them seem to effect 0 rows, etc.  I assume the shard update in question is “2020-04-07-00-Add-Order-To-Biota-Properties-Palette" which I had executed previously and the table looks like:

+----------------+-------------------+------+-----+---------+----------------+

| Field          | Type              | Null | Key | Default | Extra          |

+----------------+-------------------+------+-----+---------+----------------+

| id             | int unsigned      | NO   | PRI | NULL    | auto_increment |

| object_Id      | int unsigned      | NO   | MUL | 0       |                |

| sub_Palette_Id | int unsigned      | NO   |     | NULL    |                |

| offset         | smallint unsigned | NO   |     | NULL    |                |

| length         | smallint unsigned | NO   |     | NULL    |                |

| order          | tinyint unsigned  | YES  |     | NULL    |                |

+----------------+-------------------+------+-----+---------+----------------+

 

There is nothing in the table, empty set.

 

Am I missing something, should I rebuild?  Any advice is welcome, and I hope this doesn’t reopen the ticket, that wasn’t my intent.

 

Thanks again!

**Comment by gmriggs** [comment]
@eviosdelam 

Hmm, if you ran the update, and you are still getting an error with 'order' column, maybe it's something different than I originally thought

Forwarding this to @Mag-nus , as he knows the most about this particular update
