### ISSUE TITLE
System.InvalidOperationException DbSet Weenie

### ISSUE THREAD

**Issue by veizour** [ACEmulator/ACE#3751]
### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
Attempt to create new character
Existing character appeared to function properly at the moment, though I did not test extensively.

### The log given by the failure.
2021-12-03 15:52:32,076 [World Manager] ERROR (ACE.Server.Network.Managers.InboundMessageManager) Received GameMessage packet that threw an exception from account: 1:veizour, player: , opcode: 0xF656:CharacterCreate
2021-12-03 15:52:32,076 [World Manager] ERROR (ACE.Server.Network.Managers.InboundMessageManager) System.InvalidOperationException: The LINQ expression 'DbSet<Weenie>()
    .Join(
        inner: DbSet<WeeniePropertiesString>(), 
        outerKeySelector: w => w.ClassId, 
        innerKeySelector: w0 => w0.ObjectId, 
        resultSelector: (w, w0) => new TransparentIdentifier<Weenie, WeeniePropertiesString>(
            Outer = w, 
            Inner = w0
        ))
    .Where(ti => ti.Outer.Type == 10 && (int)ti.Inner.Type == 1 && ti.Inner.Value.Equals(
        value: __name_0, 
        comparisonType: InvariantCultureIgnoreCase))' could not be translated. Additional information: Translation of the 'String.Equals' overload with a 'StringComparison' parameter is not supported by default. To opt-in to translations of methods with a 'StringComparison' parameter, call `EnableStringComparisonTranslations` on your MySQL specific 'DbContext' options. For general EF Core information about this error, see https://go.microsoft.com/fwlink/?linkid=2129535 for more information. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|15_0(ShapedQueryExpression translated, <>c__DisplayClass15_0& )
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
   at ACE.Database.WorldDatabaseWithEntityCache.IsCreatureNameInWorldDatabase(WorldDbContext context, String name) in /Source/ACE.Database/WorldDatabaseWithEntityCache.cs:line 266
   at ACE.Database.WorldDatabaseWithEntityCache.IsCreatureNameInWorldDatabase(String name) in /Source/ACE.Database/WorldDatabaseWithEntityCache.cs:line 260
   at ACE.Server.Network.Handlers.CharacterHandler.CharacterCreateEx(ClientMessage message, Session session) in /Source/ACE.Server/Network/Handlers/CharacterHandler.cs:line 57
   at ACE.Server.Network.Handlers.CharacterHandler.CharacterCreate(ClientMessage message, Session session) in /Source/ACE.Server/Network/Handlers/CharacterHandler.cs:line 41
   at ACE.Server.Network.Managers.InboundMessageManager.<>c__DisplayClass10_0.<HandleClientMessage>b__0() in /Source/ACE.Server/Network/Managers/InboundMessageManager.cs:line 105

### Desired functionality.
Requesting a Docker Hub tag generated for the last update prior to this one so I can reference that update and continue gaming.
(i.e. instead of acemulator/ace:latest, maybe acemulator/ace:laststable or acemulator/ace:v1.34.4121 or something)
v1.34.4121
Not sure if it was the newest update or that update that caused the issue.
As this is just a Docker tag, I was hoping this wouldn't require anything time consuming or troublesome.
Appreciated!

**Comment by LtRipley36706** [comment]
fixed in #3752
