### ISSUE TITLE
System.InvalidCastException error on fresh install start up

### ISSUE THREAD

**Issue by KeySleep** [ACEmulator/ACE#3908]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
- Install Server files from ACE.Server-v1.47.4269 and add .dats
- Create databases in MariaDB using SQLYog
- Import base .sql scripts for auth and shard from base files
- Import base .sql script for world from ACE-World-Database-v0.9.260.sql
- configure config.js and log4net.config files
- Start server
Server halts with System.InvalidCastException error

### The log given by the failure.
2022-09-30 16:07:39,882 [1] INFO  (ACE.Server.Program) Starting ACEmulator...
2022-09-30 16:07:39,898 [1] INFO  (ACE.Server.Program) Initializing ConfigManager...
2022-09-30 16:07:40,005 [1] INFO  (ACE.Server.Program) Pruning invalid friends from all friend lists...
2022-09-30 16:07:41,058 [1] INFO  (ACE.Server.Program) Pruned 0 invalid friends found on friend lists.
2022-09-30 16:07:41,060 [1] INFO  (ACE.Server.Program) Automatic Server version check started...
2022-09-30 16:07:41,271 [1] INFO  (ACE.Server.Program) Current Server Binary: 1.47.4269.20220920005841-master-6da54f0
2022-09-30 16:07:41,678 [1] INFO  (ACE.Server.Program) Latest Server Version is v1.47.4269 -- No Update Required!
2022-09-30 16:07:41,680 [1] INFO  (ACE.Server.Program) Automatic World Database Update started...
2022-09-30 16:07:41,721 [1] INFO  (ACE.Server.Program) Current World Database version: Base - v0.8.5 | Patch - v0.9.260
2022-09-30 16:07:41,977 [1] INFO  (ACE.Server.Program) Latest patch version is v0.9.260 -- No Update Required!
2022-09-30 16:07:41,977 [1] INFO  (ACE.Server.Program) Automatic World Database Update complete.
2022-09-30 16:07:42,046 [1] ERROR (ACE.Server.Program) System.InvalidCastException: Object cannot be cast from DBNull to other types.
   at System.DBNull.System.IConvertible.ToInt32(IFormatProvider provider)
   at MySql.Data.MySqlClient.Driver.LoadCharacterSets(MySqlConnection connection)
   at MySql.Data.MySqlClient.Driver.Configure(MySqlConnection connection)
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at ACE.Server.Program.GetContentFolder() in C:\projects\ace\Source\ACE.Server\Program_DbUpdates.cs:line 153
   at ACE.Server.Program.AutoApplyWorldCustomizations() in C:\projects\ace\Source\ACE.Server\Program_DbUpdates.cs:line 185
   at ACE.Server.Program.Main(String[] args) in C:\projects\ace\Source\ACE.Server\Program.cs:line 205

### Mention any other details that might be useful.
Server is a stand alone Win10 box, current updates and .NET/.ASP runtimes for v4-v6.

**Comment by KeySleep** [comment]
Following a post in discord, the problem has been identified as caused by MariaDB v 1.10.x.  Rolling back to 10.8 or 10.6 resolves the issue.
